Loaded dependency [python3/3.10.7]: gcc/11.3.0-binutils-2.38
Loaded module: python3/3.10.7

Loading python3/3.10.7
  Loading requirement: gcc/11.3.0-binutils-2.38
Loaded module: cuda/12.0
Loaded module: cudnn/v8.3.2.44-prod-cuda-11.X
/zhome/6b/b/151617/env2/lib/python3.10/site-packages/torch/utils/data/dataloader.py:561: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Traceback (most recent call last):
  File "/zhome/6b/b/151617/Sign2Text/main.py", line 72, in <module>
    main()
  File "/zhome/6b/b/151617/Sign2Text/main.py", line 65, in main
    train(model, dataloader_train, dataloader_val, T_CFG)
  File "/zhome/6b/b/151617/Sign2Text/Trainer/trainer.py", line 69, in train
    model, optimizer, scheduler, current_epoch, epoch_losses, val_b4 = load_checkpoint(CFG.load_checkpoint_path, model, optimizer, scheduler)
  File "/zhome/6b/b/151617/Sign2Text/utils/load_checkpoint.py", line 4, in load_checkpoint
    checkpoint = torch.load(path)
  File "/zhome/6b/b/151617/env2/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/zhome/6b/b/151617/env2/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/zhome/6b/b/151617/env2/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/work3/s200925/Sign2Text/final_training/Sign2Text_Epoch7_loss_-467.0415774851265_B4_0.12160461981082381'
